export const BROWSERS = ['Chrome', 'Firefox', 'Safari', 'Edge', 'Opera'];
export const OS_NAMES = ['Windows', 'macOS', 'Linux', 'Android', 'iOS'];
export const DEVICE_TYPES = ['desktop', 'mobile', 'tablet'];
// Custom events that would be tracked via track() calls
export const CUSTOM_EVENTS = [
	'click',
	'button_click',
	'form_submit',
	'signup',
	'login',
	'logout',
	'purchase',
	'add_to_cart',
	'remove_from_cart',
	'checkout_started',
	'search',
	'filter_applied',
	'video_play',
	'video_pause',
	'download',
	'newsletter_signup',
	'contact_form',
	'feature_toggle',
	'share',
	'error_occurred',
	'api_call',
	'user_interaction',
];

export const BLOG_CATEGORIES = [
	'tech',
	'business',
	'marketing',
	'design',
	'development',
	'startup',
	'ai',
	'saas',
	'mobile',
	'web',
	'data',
	'security',
	'cloud',
	'api',
	'tutorial',
];

export const PRODUCT_CATEGORIES = [
	'software',
	'hardware',
	'books',
	'courses',
	'templates',
	'tools',
	'services',
	'consulting',
	'hosting',
	'analytics',
];

export const COMPANY_SECTIONS = [
	'about',
	'team',
	'careers',
	'investors',
	'press',
	'contact',
	'support',
	'help',
	'faq',
	'terms',
	'privacy',
	'security',
	'status',
];

export const REFERRERS = [
		'direct',
		'https://google.com/search',
		'https://www.google.com/search',
		'https://bing.com/search',
		'https://duckduckgo.com',
		'https://yahoo.com/search',
		'https://facebook.com',
		'https://www.facebook.com',
		'https://twitter.com',
		'https://x.com',
		'https://linkedin.com',
		'https://www.linkedin.com',
		'https://instagram.com',
		'https://reddit.com',
		'https://www.reddit.com',
		'https://youtube.com',
		'https://tiktok.com',
		'https://github.com',
		'https://stackoverflow.com',
		'https://medium.com',
		'https://dev.to',
		'https://hackernews.com',
		'https://producthunt.com',
		'https://indiehackers.com',
		'https://techcrunch.com',
		'https://vercel.com',
		'https://netlify.com',
		'https://aws.amazon.com',
		'https://cloud.google.com',
		'https://azure.microsoft.com',
		'https://digitalocean.com',
		'https://heroku.com',
		'https://railway.app',
		'https://planetscale.com',
		'https://supabase.com',
		'https://clerk.com',
		'https://auth0.com',
		'https://stripe.com',
		'https://paddle.com',
		'https://lemonsqueezy.com',
		'https://gumroad.com',
		'https://mailchimp.com',
		'https://convertkit.com',
		'https://substack.com',
		'https://notion.so',
		'https://airtable.com',
		'https://figma.com',
		'https://canva.com',
		'https://discord.com',
		'https://slack.com',
		'https://telegram.org',
		'https://whatsapp.com',
];
